# Development values for Kubelens
# Minimal resource configuration for local/dev environments

# Server configuration
server:
  enabled: true
  replicaCount: 1
  
  image:
    repository: kubelens/server
    pullPolicy: Always  # Always pull latest for development
    tag: "latest"
  
  service:
    type: ClusterIP
    port: 8080
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  env:
    - name: PORT
      value: "8080"
    - name: LOG_LEVEL
      value: "debug"  # Verbose logging for development
    - name: DATABASE_PATH
      value: "/data/kubelens.db"
  
  persistence:
    enabled: true
    storageClass: ""  # Use default storage class
    accessMode: ReadWriteOnce
    size: 1Gi
  
  affinity: {}
  tolerations: []
  nodeSelector: {}

# App configuration
app:
  enabled: true
  replicaCount: 1
  
  image:
    repository: kubelens/app
    pullPolicy: Always  # Always pull latest for development
    tag: "latest"
  
  service:
    type: ClusterIP
    port: 80
  
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 50m
      memory: 64Mi
  
  affinity: {}
  tolerations: []
  nodeSelector: {}

# Ingress - disabled for local development (use port-forward instead)
ingress:
  enabled: false

# Service Account
serviceAccount:
  create: true
  annotations: {}
  name: ""

# RBAC - full access for development
rbac:
  create: true
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]

# Global settings
global:
  imagePullSecrets: []

