releases:
- name: kubelens
  namespace: kubelens
  chart: ./charts/kubelens
  version: 0.1.0
  createNamespace: true
  values:
    - app:
        ingress:
          enabled: true
          className: "nginx"
          annotations: {}
          hosts:
            - host: kubelens.app
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: kubelens-app-cert
              hosts:
                - kubelens.app