releases:
- name: kubelens
  namespace: kubelens
  chart: ./charts/kubelens
  version: 0.1.0
  createNamespace: true
  values:
    - app:
        ingress:
          enabled: true
          className: "nginx"
          annotations: {}
            # cert-manager.io/cluster-issuer: cloudflare-cluster-issuer
            # nginx.ingress.kubernetes.io/ssl-redirect: "true"
          hosts:
            - host: kubelens.app
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: kubelens-app-secret
              hosts:
                - kubelens.app