replicaCount: 1

image:
  repository: kubelensai/kubelens-app
  pullPolicy: IfNotPresent
  tag: ""  # Defaults to chart appVersion

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
    # cert-manager.io/cluster-issuer: letsencrypt-prod
    # nginx.ingress.kubernetes.io/ssl-redirect: "true"
  hosts:
    - host: kubelens.example.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: kubelens-tls
      hosts:
        - kubelens.example.com

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

podAnnotations: {}

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: false  # Node.js needs write access for temp files
  runAsNonRoot: true
  runAsUser: 1000  # node user

nodeSelector: {}

tolerations: []

affinity: {}

livenessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 10
  periodSeconds: 10
  timeoutSeconds: 5
  failureThreshold: 3

readinessProbe:
  httpGet:
    path: /
    port: http
  initialDelaySeconds: 5
  periodSeconds: 5
  timeoutSeconds: 3
  failureThreshold: 3

# Environment variables
env:
  # API Server URL - will be auto-configured if not set
  # For standalone deployment: http://kubelens-server:8080
  # For parent chart deployment: will be set automatically
  apiServer: ""
  # Extra environment variables
  extra: {}
    # CUSTOM_VAR: "value"

# Server service configuration (for parent chart integration)
server:
  # Server service name (auto-detected from Release.Name in parent chart)
  serviceName: ""
  servicePort: 8080
