{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubelens.fullname" . }}
  labels:
    {{- include "kubelens.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
    - nodes
    - namespaces
    - pods
    - pods/log
    - services
    - endpoints
    - secrets
    - configmaps
    - events
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources:
    - deployments
    - daemonsets
    - statefulsets
    - replicasets
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources:
    - jobs
    - cronjobs
  verbs: ["get", "list", "watch"]
- apiGroups: ["networking.k8s.io"]
  resources:
    - ingresses
  verbs: ["get", "list", "watch"]
- apiGroups: ["storage.k8s.io"]
  resources:
    - storageclasses
    - persistentvolumes
    - persistentvolumeclaims
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubelens.fullname" . }}
  labels:
    {{- include "kubelens.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kubelens.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kubelens.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}

