name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-server:
    name: Test Server (Go)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache-dependency-path: src/server/go.sum

      - name: Download dependencies
        working-directory: ./src/server
        run: go mod download

      - name: Run tests
        working-directory: ./src/server
        run: go test -v -race -coverprofile=coverage.out ./...

      - name: Upload coverage
        uses: codecov/codecov-action@v4
        with:
          files: ./src/server/coverage.out
          flags: server
          fail_ci_if_error: false

  test-app:
    name: Test App (React)
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: src/app/package-lock.json

      - name: Install dependencies
        working-directory: ./src/app
        run: npm ci

      - name: Run linter
        working-directory: ./src/app
        run: npm run lint || true

      - name: Build app
        working-directory: ./src/app
        run: npm run build

  lint-helm:
    name: Lint Helm Charts
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'latest'

      - name: Lint Helm charts
        run: |
          cd charts/kubelens
          helm dependency build
          helm lint .
          helm template kubelens . --debug

