name: Helm Deploy

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  helm-deploy:
    name: Helm Deploy Kubelens
    runs-on: ubuntu-24.04
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy with Helmfile
        uses: helmfile/helmfile-action@v2
        with:
          helmfile-args: apply
        env:
          KUBECONFIG: '${{ secrets.KUBECONFIG }}'